// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Model/observation_model.dart';
import 'Model/profile_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 772790432831363200),
    name: 'Observation',
    lastPropertyId: const obx_int.IdUid(12, 2607764768017297121),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5994011507338174104),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4993825300972376930),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5841578007943985996),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 607445508112957863),
        name: 'lat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 512912807780372224),
        name: 'lng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2398590521603114213),
        name: 'locationText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5200380331819315033),
        name: 'durationSec',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8228400162346921681),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4354459301988545309),
        name: 'skyCondition',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1362276110423732805),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2295883228648068929),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2607764768017297121),
        name: 'audioPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7544942485870478489),
    name: 'Profile',
    lastPropertyId: const obx_int.IdUid(6, 8097960399269128311),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3780440496560973337),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2316377640182318168),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9012235111276418130),
        name: 'lastName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9030177752727922491),
        name: 'studentId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4294514579273688452),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8097960399269128311),
        name: 'phrase',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7544942485870478489),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Observation: obx_int.EntityDefinition<Observation>(
      model: _entities[0],
      toOneRelations: (Observation object) => [],
      toManyRelations: (Observation object) => {},
      getId: (Observation object) => object.id,
      setId: (Observation object, int id) {
        object.id = id;
      },
      objectToFB: (Observation object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final locationTextOffset = object.locationText == null
            ? null
            : fbb.writeString(object.locationText!);
        final categoryOffset = fbb.writeString(object.category);
        final skyConditionOffset = fbb.writeString(object.skyCondition);
        final descriptionOffset = fbb.writeString(object.description);
        final imagePathOffset = fbb.writeString(object.imagePath);
        final audioPathOffset = fbb.writeString(object.audioPath);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
        fbb.addFloat64(3, object.lat);
        fbb.addFloat64(4, object.lng);
        fbb.addOffset(5, locationTextOffset);
        fbb.addInt64(6, object.durationSec);
        fbb.addOffset(7, categoryOffset);
        fbb.addOffset(8, skyConditionOffset);
        fbb.addOffset(9, descriptionOffset);
        fbb.addOffset(10, imagePathOffset);
        fbb.addOffset(11, audioPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final skyConditionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final locationTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final lngParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final latParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final durationSecParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          isUtc: true,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final audioPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final object = Observation(
          id: idParam,
          title: titleParam,
          skyCondition: skyConditionParam,
          locationText: locationTextParam,
          lng: lngParam,
          lat: latParam,
          imagePath: imagePathParam,
          durationSec: durationSecParam,
          description: descriptionParam,
          dateTime: dateTimeParam,
          category: categoryParam,
          audioPath: audioPathParam,
        );

        return object;
      },
    ),
    Profile: obx_int.EntityDefinition<Profile>(
      model: _entities[1],
      toOneRelations: (Profile object) => [],
      toManyRelations: (Profile object) => {},
      getId: (Profile object) => object.id,
      setId: (Profile object, int id) {
        object.id = id;
      },
      objectToFB: (Profile object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final lastNameOffset = fbb.writeString(object.lastName);
        final studentIdOffset = fbb.writeString(object.studentId);
        final imagePathOffset = fbb.writeString(object.imagePath);
        final phraseOffset = fbb.writeString(object.phrase);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, lastNameOffset);
        fbb.addOffset(3, studentIdOffset);
        fbb.addOffset(4, imagePathOffset);
        fbb.addOffset(5, phraseOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final studentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final phraseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = Profile(
          id: idParam,
          name: nameParam,
          lastName: lastNameParam,
          studentId: studentIdParam,
          imagePath: imagePathParam,
          phrase: phraseParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Observation] entity fields to define ObjectBox queries.
class Observation_ {
  /// See [Observation.id].
  static final id = obx.QueryIntegerProperty<Observation>(
    _entities[0].properties[0],
  );

  /// See [Observation.title].
  static final title = obx.QueryStringProperty<Observation>(
    _entities[0].properties[1],
  );

  /// See [Observation.dateTime].
  static final dateTime = obx.QueryDateProperty<Observation>(
    _entities[0].properties[2],
  );

  /// See [Observation.lat].
  static final lat = obx.QueryDoubleProperty<Observation>(
    _entities[0].properties[3],
  );

  /// See [Observation.lng].
  static final lng = obx.QueryDoubleProperty<Observation>(
    _entities[0].properties[4],
  );

  /// See [Observation.locationText].
  static final locationText = obx.QueryStringProperty<Observation>(
    _entities[0].properties[5],
  );

  /// See [Observation.durationSec].
  static final durationSec = obx.QueryIntegerProperty<Observation>(
    _entities[0].properties[6],
  );

  /// See [Observation.category].
  static final category = obx.QueryStringProperty<Observation>(
    _entities[0].properties[7],
  );

  /// See [Observation.skyCondition].
  static final skyCondition = obx.QueryStringProperty<Observation>(
    _entities[0].properties[8],
  );

  /// See [Observation.description].
  static final description = obx.QueryStringProperty<Observation>(
    _entities[0].properties[9],
  );

  /// See [Observation.imagePath].
  static final imagePath = obx.QueryStringProperty<Observation>(
    _entities[0].properties[10],
  );

  /// See [Observation.audioPath].
  static final audioPath = obx.QueryStringProperty<Observation>(
    _entities[0].properties[11],
  );
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id = obx.QueryIntegerProperty<Profile>(
    _entities[1].properties[0],
  );

  /// See [Profile.name].
  static final name = obx.QueryStringProperty<Profile>(
    _entities[1].properties[1],
  );

  /// See [Profile.lastName].
  static final lastName = obx.QueryStringProperty<Profile>(
    _entities[1].properties[2],
  );

  /// See [Profile.studentId].
  static final studentId = obx.QueryStringProperty<Profile>(
    _entities[1].properties[3],
  );

  /// See [Profile.imagePath].
  static final imagePath = obx.QueryStringProperty<Profile>(
    _entities[1].properties[4],
  );

  /// See [Profile.phrase].
  static final phrase = obx.QueryStringProperty<Profile>(
    _entities[1].properties[5],
  );
}
